nim:
  g: 10 # number of games in a batch
  p: 1 # starting player option
  m: 0 # number of simulations (and hence rollouts) per actual game move
  n: 10 # starting number of pieces/stones in each game
  k: 10 # maximum number of pieces that either player can take on their turn (min 1)

oldgold:
  g: 10 # number of games in a batch
  b_init: [1, 1, 0, 0, 2, 1, 1, 1, 0, 1] # initial board configuration
  p: 1 # starting player option
  m: 0 # number of simulations (and hence rollouts) per actual game move

verbose: True
